version: "3.7"

services:

  app_proxy:
    environment:
      APP_HOST: toalt23-zec-mining-pool_web_1
      APP_PORT: 3000

  web:
    image: toalt23/zec-mining-pool-web:latest
    user: "1000:1000"
    init: true
    environment:
      ZEBRA_RPC_HOST: toalt23-zec-mining-pool_zebrad_1
      ZEBRA_RPC_PORT: "8232"
    restart: on-failure
    depends_on:
      - zebrad

  zebrad:
    image: zfnd/zebra:latest
    init: true
    cpus: "3.0"
    environment:
      ZEBRA_RPC__LISTEN_ADDR: "0.0.0.0:8232"
      ZEBRA_RPC__ENABLE_COOKIE_AUTH: "false"
      ZEBRA_SYNC__PARALLEL_CPU_THREADS: "2"
      ZEBRA_SYNC__FULL_VERIFY_CONCURRENCY_LIMIT: "1"
    volumes:
      - ${APP_DATA_DIR}/zebrad-cache:/home/zebra/.cache/zebra
    restart: on-failure