version: "3.7"

services:

  app_proxy:
    environment:
      APP_HOST: toalt23-zec-mining-pool_web_1
      APP_PORT: 3000

  web:
    image: toalt23/zec-mining-pool-web:latest
    user: "1000:1000"
    init: true
    environment:
      ZEBRA_RPC_HOST: toalt23-zec-mining-pool_zakura_1
      ZEBRA_RPC_PORT: "8232"
    restart: on-failure
    depends_on:
      - zakura

  zakura:
    image: zakuracore/zakura:latest
    init: true
    cpus: "3.0"
    environment:
      ZAKURA_RPC__LISTEN_ADDR: "0.0.0.0:8232"
      ZAKURA_RPC__ENABLE_COOKIE_AUTH: "false"
      ZAKURA_SYNC__PARALLEL_CPU_THREADS: "3"
    volumes:
      - ${APP_DATA_DIR}/zakura-cache:/home/zebra/.cache/zakura
    restart: on-failure